/**
 * React Hot Toast Notification Utility
 * Using react-hot-toast library for modern toast notifications
 */
import { toast as hotToast } from 'react-hot-toast';

/**
 * Toast notification utilities
 */
export const notification = {
  /**
   * Success notification
   * @param {string} title - Notification title
   * @param {string} message - Optional message
   * @param {object} options - Override options
   */
  success: (title, message = '', options = {}) => {
    const fullMessage = message ? `${title}: ${message}` : title;
    hotToast.success(fullMessage, {
      duration: 3000,
      position: 'top-right',
      ...options
    });
  },

  /**
   * Error notification
   * @param {string} title - Notification title
   * @param {string} message - Optional message
   * @param {object} options - Override options
   */
  error: (title, message = '', options = {}) => {
    const fullMessage = message ? `${title}: ${message}` : title;
    hotToast.error(fullMessage, {
      duration: 5000,
      position: 'top-right',
      ...options
    });
  },

  /**
   * Warning notification
   * @param {string} title - Notification title
   * @param {string} message - Optional message
   * @param {object} options - Override options
   */
  warning: (title, message = '', options = {}) => {
    const fullMessage = message ? `${title}: ${message}` : title;
    hotToast(fullMessage, {
      icon: '⚠️',
      duration: 4000,
      position: 'top-right',
      style: {
        background: '#fbbf24',
        color: '#1f2937',
      },
      ...options
    });
  },

  /**
   * Info notification
   * @param {string} title - Notification title
   * @param {string} message - Optional message
   * @param {object} options - Override options
   */
  info: (title, message = '', options = {}) => {
    const fullMessage = message ? `${title}: ${message}` : title;
    hotToast(fullMessage, {
      icon: 'ℹ️',
      duration: 3000,
      position: 'top-right',
      style: {
        background: '#3b82f6',
        color: '#ffffff',
      },
      ...options
    });
  },

  /**
   * Purchase Order specific notifications
   */
  po: {
    created: (poData) => {
      notification.success(
        '📦 Purchase Order Created!', 
        `PO ID: ${poData.po_id || 'N/A'} | Total: ₹${poData.total_amount || '0.00'}`,
        { duration: 5000 }
      );
    },
    
    autoGenerated: (poData, moReference) => {
      notification.success(
        '🔄 Auto-generated PO Created!', 
        `Generated from ${moReference} | Quantity: ${poData.quantity_ordered} kg`,
        { duration: 6000 }
      );
    },
    
    error: (error) => {
      notification.error(
        'PO Creation Failed', 
        error.message || 'Unable to create purchase order'
      );
    }
  },

  /**
   * Manufacturing Order specific notifications
   */
  mo: {
    created: (moData) => {
      notification.success(
        '🏭 Manufacturing Order Created!', 
        `MO ID: ${moData.mo_id || 'N/A'} | Quantity: ${moData.quantity || 'N/A'}`,
        { duration: 5000 }
      );
    },
    
    stockInsufficient: (shortage) => {
      notification.warning(
        '⚠️ Insufficient Stock', 
        `Shortage: ${shortage} kg. Create PO to fulfill requirement.`,
        { duration: 6000 }
      );
    },
    
    error: (error) => {
      notification.error(
        'MO Creation Failed', 
        error.message || 'Unable to create manufacturing order'
      );
    }
  },

  /**
   * Navigation notifications
   */
  navigation: {
    redirecting: (destination) => {
      notification.info(`🧭 Redirecting to ${destination}...`, '', {
        duration: 2000
      });
    }
  }
};

// Export both 'toast' and 'notification' for backward compatibility
export const toast = notification;

export default notification;