/**
 * NotifyX Toast Notification Utility
 * Using NotifyX library for modern toast notifications
 */
import { NotifyX } from 'notifyx';

// Debug: Check if NotifyX is properly imported
console.log('NotifyX imported:', NotifyX);
console.log('Available NotifyX methods:', Object.getOwnPropertyNames(NotifyX));

/**
 * Toast notification utilities
 */
export const toast = {
  /**
   * Success notification
   * @param {string} title - Notification title
   * @param {string} message - Optional message
   * @param {object} options - Override options
   */
  success: (title, message = '', options = {}) => {
    try {
      console.log('Calling NotifyX.success with:', title, message);
      NotifyX.success(message ? `${title}: ${message}` : title, {
        position: 'top-right',
        duration: 3000,
        dismissible: true,
        ...options
      });
    } catch (error) {
      console.error('NotifyX.success error:', error);
      // Fallback to console.log if NotifyX fails
      console.log(`SUCCESS: ${title}${message ? ': ' + message : ''}`);
    }
  },

  /**
   * Error notification
   * @param {string} title - Notification title
   * @param {string} message - Optional message
   * @param {object} options - Override options
   */
  error: (title, message = '', options = {}) => {
    NotifyX.error(message ? `${title}: ${message}` : title, {
      position: 'top-right',
      duration: 5000,
      dismissible: true,
      ...options
    });
  },

  /**
   * Warning notification
   * @param {string} title - Notification title
   * @param {string} message - Optional message
   * @param {object} options - Override options
   */
  warning: (title, message = '', options = {}) => {
    NotifyX.warning(message ? `${title}: ${message}` : title, {
      position: 'top-right',
      duration: 4000,
      dismissible: true,
      ...options
    });
  },

  /**
   * Info notification
   * @param {string} title - Notification title
   * @param {string} message - Optional message
   * @param {object} options - Override options
   */
  info: (title, message = '', options = {}) => {
    try {
      console.log('Calling NotifyX.info with:', title, message);
      NotifyX.info(message ? `${title}: ${message}` : title, {
        position: 'top-right',
        duration: 3000,
        dismissible: true,
        ...options
      });
    } catch (error) {
      console.error('NotifyX.info error:', error);
      // Fallback to console.log if NotifyX fails
      console.log(`INFO: ${title}${message ? ': ' + message : ''}`);
    }
  },

  /**
   * Purchase Order specific notifications
   */
  po: {
    created: (poData) => {
      toast.success(
        '📦 Purchase Order Created!', 
        `PO ID: ${poData.po_id || 'N/A'} | Total: ₹${poData.total_amount || '0.00'}`,
        { duration: 5000 }
      );
    },
    
    autoGenerated: (poData, moReference) => {
      toast.success(
        '🔄 Auto-generated PO Created!', 
        `Generated from ${moReference} | Quantity: ${poData.quantity_ordered} kg`,
        { duration: 6000 }
      );
    },
    
    error: (error) => {
      toast.error(
        'PO Creation Failed', 
        error.message || 'Unable to create purchase order'
      );
    }
  },

  /**
   * Manufacturing Order specific notifications
   */
  mo: {
    created: (moData) => {
      toast.success(
        '🏭 Manufacturing Order Created!', 
        `MO ID: ${moData.mo_id || 'N/A'} | Quantity: ${moData.quantity || 'N/A'}`,
        { duration: 5000 }
      );
    },
    
    stockInsufficient: (shortage) => {
      toast.warning(
        '⚠️ Insufficient Stock', 
        `Shortage: ${shortage} kg. Create PO to fulfill requirement.`,
        { duration: 6000 }
      );
    },
    
    error: (error) => {
      toast.error(
        'MO Creation Failed', 
        error.message || 'Unable to create manufacturing order'
      );
    }
  },

  /**
   * Navigation notifications
   */
  navigation: {
    redirecting: (destination) => {
      try {
        console.log('Calling NotifyX.info for navigation:', destination);
        NotifyX.info(`🧭 Redirecting to ${destination}...`, {
          position: 'top-right',
          duration: 2000,
          dismissible: true
        });
      } catch (error) {
        console.error('NotifyX.info navigation error:', error);
        // Fallback to console.log if NotifyX fails
        console.log(`NAVIGATION: Redirecting to ${destination}...`);
      }
    }
  }
};

export default toast;
